version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "18000:18000"
    depends_on:
      - db